import type { ProductCreateInput } from './product-schema';

export function demoProducts(): ProductCreateInput[] {
  return [
    {
      sku: 'flower-orchid-001',
      title: 'White Orchid Arrangement',
      summary: 'Fresh orchid arrangement for same-day local delivery.',
      brand: 'OCP Florist',
      category: 'flowers',
      image_urls: ['https://commerce-provider.example.test/images/flower-orchid-001.jpg'],
      currency: 'USD',
      amount: 48,
      availability_status: 'in_stock',
      quantity: 18,
      status: 'active',
      attributes: { delivery_area: 'local', occasion: 'gift' },
    },
    {
      sku: 'electronics-headphones-001',
      title: 'Noise Cancelling Headphones',
      summary: 'Wireless over-ear headphones with travel case.',
      brand: 'North Audio',
      category: 'electronics',
      image_urls: ['https://commerce-provider.example.test/images/electronics-headphones-001.jpg'],
      currency: 'USD',
      amount: 129,
      availability_status: 'low_stock',
      quantity: 4,
      status: 'active',
      attributes: { color: 'black', warranty_months: 24 },
    },
    {
      sku: 'grocery-coffee-001',
      title: 'Single Origin Coffee Beans',
      summary: 'Whole bean coffee roasted this week.',
      brand: 'Harbor Roast',
      category: 'grocery',
      image_urls: ['https://commerce-provider.example.test/images/grocery-coffee-001.jpg'],
      currency: 'USD',
      amount: 17.5,
      availability_status: 'in_stock',
      quantity: 42,
      status: 'active',
      attributes: { weight_grams: 340, origin: 'Colombia' },
    },
    {
      sku: 'gift-card-digital-001',
      title: 'Digital Gift Card',
      summary: 'Email-delivered store credit redeemable online.',
      brand: 'Demo Commerce',
      category: 'digital gift card',
      image_urls: ['https://commerce-provider.example.test/images/gift-card-digital-001.jpg'],
      currency: 'USD',
      amount: 50,
      availability_status: 'in_stock',
      quantity: 999,
      status: 'active',
      attributes: { delivery: 'email', redeemable_online: true },
    },
    {
      sku: 'service-bike-tuneup-001',
      title: 'Local Bicycle Tune-Up',
      summary: 'Book a mechanic slot for a standard bicycle tune-up.',
      brand: 'Neighborhood Workshop',
      category: 'local service',
      image_urls: ['https://commerce-provider.example.test/images/service-bike-tuneup-001.jpg'],
      currency: 'USD',
      amount: 75,
      availability_status: 'preorder',
      quantity: 8,
      status: 'active',
      attributes: { appointment_required: true, duration_minutes: 60 },
    },
  ];
}
