import { index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';

export const ocpActivityPublicVisibility = pgEnum('ocp_activity_public_visibility', ['public', 'aggregate_only', 'private']);

export const ocpActivityRawEvents = pgTable('ocp_activity_events_raw', {
  id: text('id').primaryKey(),
  eventVersion: text('event_version').notNull(),
  eventType: text('event_type').notNull(),
  idempotencyKey: text('idempotency_key'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
  observedAt: timestamp('observed_at', { withTimezone: true }).notNull().defaultNow(),
  correlationId: text('correlation_id'),
  traceId: text('trace_id'),
  spanId: text('span_id'),
  parentEventId: text('parent_event_id'),
  sourceKind: text('source_kind').notNull(),
  clientKind: text('client_kind').notNull(),
  endpointRole: text('endpoint_role').notNull(),
  protocolFamily: text('protocol_family').notNull(),
  protocolVersion: text('protocol_version'),
  method: text('method'),
  pathTemplate: text('path_template'),
  statusCode: integer('status_code'),
  durationMs: integer('duration_ms'),
  errorCode: text('error_code'),
  registrationId: text('registration_id'),
  catalogId: text('catalog_id'),
  providerId: text('provider_id'),
  objectType: text('object_type'),
  queryPack: text('query_pack'),
  capabilityId: text('capability_id'),
  resultCount: integer('result_count'),
  syncObjectCount: integer('sync_object_count'),
  publicVisibility: ocpActivityPublicVisibility('public_visibility').notNull().default('aggregate_only'),
  redactionPolicyVersion: text('redaction_policy_version').notNull(),
  payloadHash: text('payload_hash'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  rawEvent: jsonb('raw_event').$type<Record<string, unknown>>().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  idempotencyUnique: uniqueIndex('ocp_activity_events_raw_idempotency_unique').on(table.idempotencyKey),
  typeOccurredIdx: index('ocp_activity_events_raw_type_occurred_idx').on(table.eventType, table.occurredAt),
  protocolOccurredIdx: index('ocp_activity_events_raw_protocol_occurred_idx').on(table.protocolFamily, table.occurredAt),
  catalogOccurredIdx: index('ocp_activity_events_raw_catalog_occurred_idx').on(table.catalogId, table.occurredAt),
  providerOccurredIdx: index('ocp_activity_events_raw_provider_occurred_idx').on(table.providerId, table.occurredAt),
  correlationIdx: index('ocp_activity_events_raw_correlation_idx').on(table.correlationId),
}));

export const ocpActivityPublicEvents = pgTable('ocp_activity_public_events', {
  id: text('id').primaryKey(),
  rawEventId: text('raw_event_id')
    .notNull()
    .references(() => ocpActivityRawEvents.id, { onDelete: 'cascade' }),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
  eventType: text('event_type').notNull(),
  sourceKind: text('source_kind').notNull(),
  clientKind: text('client_kind').notNull(),
  protocolFamily: text('protocol_family').notNull(),
  catalogId: text('catalog_id'),
  providerId: text('provider_id'),
  objectType: text('object_type'),
  statusClass: text('status_class').notNull(),
  durationBucket: text('duration_bucket').notNull(),
  resultCountBucket: text('result_count_bucket').notNull(),
  publicSummary: text('public_summary').notNull(),
  correlationIdHash: text('correlation_id_hash'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  rawEventUnique: uniqueIndex('ocp_activity_public_events_raw_unique').on(table.rawEventId),
  occurredIdx: index('ocp_activity_public_events_occurred_idx').on(table.occurredAt),
  typeOccurredIdx: index('ocp_activity_public_events_type_occurred_idx').on(table.eventType, table.occurredAt),
  protocolOccurredIdx: index('ocp_activity_public_events_protocol_occurred_idx').on(table.protocolFamily, table.occurredAt),
  catalogOccurredIdx: index('ocp_activity_public_events_catalog_occurred_idx').on(table.catalogId, table.occurredAt),
}));
